name: texlive # you probably want to 'snapcraft register <name>'
base: core20
version: '0.6'
summary: TeX Live, a LaTeX distribution and package manager
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: classic

apps:
  tlmgr:
    command: dist/bin/x86_64-linux/tlmgr
  pdflatex:
    command: dist/bin/x86_64-linux/pdflatex
  bibtex:
    command: dist/bin/x86_64-linux/bibtex

parts:
  texlive:
    source: .
    plugin: make
    build-packages:
      - build-essential
      - wget
    stage-packages:
      - libfontconfig1
      - libfreetype6
      - libice6
      - libpng16-16
      - libsm6
      - libx11-6
      - libxau6
      - libxaw7
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxmu6
      - libxpm4
      - libxt6
